sudo: required
dist: trusty
addons:
  chrome: stable
languages: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  gulp karma-test
  gulp webpack-prod
