sudo: required
dist: trusty
addons:
  chrome: stable
languages: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp-cli
install:
  - npm install
script:
  - gulp webpack-prod
  - gulp karma-test
  - gulp print-coverage
after_success:
  - gulp clean
  - npm install
  - gulp webpack-prod
